---
title: Exploratory Study of Island-Based Parallel Differential Evolution Algorithms using Apache Spark 
subtitle: Quantitative Analysis
author: 
  - Davide Anghileri \<davidean@kth.se\>
  - Nathan Consuegra \<nacon@kth.se\>
date: "2 November 2017"
header-includes:
  - \usepackage{indentfirst}
output: 
  pdf_document: 
    fig_caption: yes
    fig_crop: no
    fig_height: 3.5
    citation_package: natbib
    number_sections: yes
documentclass: article
classoption: a4paper
bibliography: bibliography.bib
biblio-style: plain
fontsize: 11pt
---

\setlength{\parindent}{0.8cm}

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F, comment = F)
```

```{r libraries, include = FALSE}
source("./libraries.R")
```

```{r functions}
csv_loader <- function(data) {
  read.csv(data, quote = "", header = T, sep = ",")
}

reached_solution <- function(data, variable) {
  # Labs for the plot
  color = "Function"
  xlab = paste(variable, " values")
  ylab = "Percentage of solutions found"
  title = paste("Percentage of solutions found with different values of ", variable)
  
  # Plotting for each value of CR or F
  n_instances <- max(data[,"Instance"])
  grouped_data <- aggregate(Stop.Reason ~ data[,1] + data[,variable], data, sum)
  
  bar = ggplot(grouped_data, 
               aes(x = as.character(grouped_data[,2]),
                   y = grouped_data[,3] / n_instances, 
                   group = as.character(grouped_data[,1]), 
                   color = as.character(grouped_data[,1])))
  bar = bar + geom_line() + geom_point()
  bar = bar + ylim(0, 1.1) + theme_light()
  bar + labs(title = title, x = xlab, y = ylab, color = color)
}

target_gap <- function(data, variable) {
  # Getting the gap and calculating the CI
  data$gap <- with(data, abs(data[,c("Score")] - data[,c("Target")]))
  mci = data %>% 
    group_by(data[,variable], data[,1]) %>% 
    summarise(
      N=n(),
      avg = mean(gap), 
      s = sd(gap),
      error = qt(0.975, N-1) * s / sqrt(N),
      lci = avg - error,
      uci = avg + error
    )
  
  # Plotting the information
  print(mci)
  mci_limits <- aes(ymax = mci$uci, ymin = mci$lci)
  mci_plot = ggplot(mci, aes(
    x = mci[,1], 
    y = avg,
    group = mci[,2],
    color = mci[,2]
  ))
  mci_plot = mci_plot + geom_point(position = position_dodge(width=0.4))
  mci_plot = mci_plot + geom_errorbar(
    mci_limits, 
    position = position_dodge(width = 5),
    width = 0.4
  )
  mci_plot = mci_plot + labs(
    title = paste("95% Confidence Interval for values of ", variable),
    x = paste(variable, " Values"), 
    y = "Gap between Target and Score",
    color = "Function"
  ) + theme_light()
  nudge_y = if(variable == "CR") 0 else 0.7
  mci_plot + geom_text_repel(force = T, nudge_y = nudge_y, nudge_x = 0.7,
    aes(label = formatC(avg, format = "e", digits =0))) 
}

avg_time <- function(data, variable) {
  # Labs for the plot
  xlab = paste(variable, " values")
  ylab = "Average execution time (s)"
  color = "Function"
  title = 
    paste("Average execution time (s) when the solution was found for", variable, "values")
  
  # Plotting for each value of CR or F
  filter_data <- data[data[,"Stop.Reason"] == 1,]
  grouped_data <- aggregate(
    Global.Time ~ filter_data[,1] + filter_data[,variable], filter_data, mean)
  
  bar = ggplot(grouped_data, 
               aes(x = as.character(grouped_data[,2]),
                   y = grouped_data[,3], 
                   group = as.character(grouped_data[,1]), 
                   color = as.character(grouped_data[,1])))
  bar = bar + geom_line() + geom_point() 
  bar = bar + theme_light()
  bar + labs(title = title, x = xlab, y = ylab, color = color)
}

class_histogram <- function(data, x,  title, xlab, ylab, ylimit = nrow(data)) {
  plot = ggplot(data, aes(x = x, fill = x)) + geom_bar() + ylim(0, ylimit)
  plot = plot + geom_text(stat = 'count', aes(label = ..count..), vjust = -1)
  plot + labs(title = title, x = xlab, y = ylab) + guides(fill = F)
}
```

```{r csv-loader}
# Loading results from outputs
cr_test = csv_loader("../source/outputs/CR-test-3_1-local150-max5000.csv")
f_test = csv_loader("../source/outputs/F-test.csv")
f_test.1 = csv_loader("../source/outputs/F-test-3_1-local150-max5000.csv")
bin_exp = csv_loader("../source/outputs/Binomial-Exponential.csv")
```

## Analysis of the mutation factor F

```{r timeF, fig.height = 5, fig.cap = "Average execution time with different values of F"}
avg_time(f_test.1, "F")
```

```{r reachedF, fig.height = 5, fig.cap = "Percentage of solutions found with different values of F"}
reached_solution(f_test.1, "F")
```

## Analysis of the crossover factor CR

```{r reachedCR, fig.height = 5, fig.cap = "Percentage of solutions found with different values of  F"}
reached_solution(cr_test, "CR")
```

```{r timeCR, fig.height = 5, fig.cap = "Average execution time with different values of CR"}
avg_time(cr_test, "CR")
```

```{r fig.height = 5}
title = "Number of solutions found per Crossover Strategy"
xlab = "Crossover Strategy"
ylab = "Number of solutions found"

filtered <- bin_exp[bin_exp$Stop.Reason != 0,]
plot = ggplot(filtered, aes(x = CRSt, y = ..count.., group = CRSt, fill = CRSt)) 
plot = plot + geom_bar() + ylim(0, 70) + theme_light()
#plot = plot + geom_text(stat = 'count', aes(label = ..count..), vjust = -1)
plot + labs(title = title, x = xlab, y = ylab) + guides(fill = F)
```

```{r fig.height = 5}
title = "Average execution time (s) on solutions found per Crossover Strategy"
xlab = "Crossover Strategy"
ylab = "Average execution time (s)"

filtered <- bin_exp[bin_exp$Stop.Reason != 0,]
grouped_data <- aggregate(Global.Time ~ filtered[,"CRSt"], filtered, mean)
plot = ggplot(grouped_data ) + geom_bar(aes(x = grouped_data[,1], y = grouped_data[,2], group = grouped_data[,1], fill = grouped_data[,1]), stat = "identity") + ylim(0, 30)
plot + labs(title = title, x = xlab, y = ylab) + guides(fill = F) + theme_light()
```